apiVersion: v1
kind: Namespace
metadata:
  name: cce-uat
  labels:
    environment: uat
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: uat-resource-quota
  namespace: cce-uat
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 4Gi
    limits.cpu: "5"
    limits.memory: 8Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: uat-limit-range
  namespace: cce-uat
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 500m
      defaultRequest:
        memory: 128Mi
        cpu: 100m
      type: Container
