apiVersion: v1
kind: Namespace
metadata:
  name: cce-uat
  labels:
    environment: uat
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: uat-resource-quota
  namespace: cce-uat
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 8Gi
    limits.cpu: "10"
    limits.memory: 12Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: uat-limit-range
  namespace: cce-uat
spec:
  limits:
    - default:
        memory: 1Gi
        cpu: "1"
      defaultRequest:
        memory: 256Mi
        cpu: 200m
      type: Container
